### ISSUE TITLE
CDN을 지원해 주세요

### ISSUE THREAD

**Issue by felinepunch** [juijs/jui-ui#478]
JQuery나 Bootstrap처럼 CDN을 지원해주면 좋겠습니다.
Windows에서 Visual Studio를 사용하고 있는데 npm을 VS랑 같이 쓰는데 문제가 있다고 하구요.
수동으로 해 보려니까 잘 안되네요. 
CDN을 사용하는 것은 잘못 설치할 일이 없어서 좋은것 같습니다.

**Comment by easylogic** [comment]
@felinepunch  
cdn 은 여기를 사용하시면 됩니다. 

https://www.jsdelivr.com/package/npm/juijs
